# 服务运行端口
server.port=8899
# 指定项目的根路径
app.working.dir=..
spring.codec.max-in-memory-size=10MB
# Redis 相关配置
spring.redis.host=${env.ISUDA_REDIS_HOST:host.docker.internal}
spring.redis.port=${env.ISUDA_REDIS_PORT:6377}
spring.redis.enable=${env.ISUDA_REDIS_ENABLE:true}
aisuda.redis.namespace=sess
spring.redis.password=${env.ISUDA_REDIS_PASSWORD}
server.servlet.session.cookie.name=isudaid

# 预设用户列表
predefined.users[0].username=admin
predefined.users[0].password=adminspassword
predefined.users[0].roles[0]=ADMIN
# 管理员
predefined.users[0].roles[1]=\u7BA1\u7406\u5458
predefined.users[0].roles[2]=DEVELOPERS
# 用户
predefined.users[0].roles[3]=\u7528\u6237
# 所有用户
predefined.users[0].roles[4]=\u6240\u6709\u7528\u6237
# 开发人员
predefined.users[0].roles[5]=\u5f00\u53d1\u4eba\u5458
# 默认密码
aisuda.default.defined.password=000000
# 加密盐值，此项参数修改会导致先前设置的密码不可用
aisuda.password.salt=
# 日志相关配置
# 本地运行时可以打开 console 日志输出
logging.console.enabled=true
logging.file.max.size=256MB
logging.file.info.path=../log/info/info.log
logging.file.debug.path=../log/debug/debug.log
logging.file.warn.path=../log/warn/warn.log
logging.file.error.path=../log/error/error.log
logging.file.access.path=../log/access/access.log
logging.async.queue.size=5000000
logging.include.caller.data=true

# 是否开启请求日志存储,目前请求日志存储在 ../log/access-debug/access-debug.log
logging.app-engine.access.enabled=true
logging.app-engine.access.path=../log/access-debug/access-debug.log
logging.app-engine.access.days=14
logging.app-engine.access.size=200MB
# 是否存储请求和响应体
logging.app-engine.access.log-body-enabled=true
# 默认存储请求体大小限制
logging.app-engine.access.cache-body-limit=4096
logging.level.reactor.netty.http.client=DEBUG
# INFO日志是否打印请求体
logging.record.request-body=true
# gzip
server.compression.enabled=true
server.compression.mime-types=text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml,application/octet-stream
server.compression.min-response-size=1024
aisuda.datasource.env=online

# 数据库配置
# 使用mysql
aisuda.datasource.type=${env.ISUDA_DB_TYPE:mysql}
aisuda.datasource.url=jdbc:${env.ISUDA_DB_TYPE:mysql}://${env.ISUDA_DB_HOST:host.docker.internal}:${env.ISUDA_DB_PORT:3304}/${env.ISUDA_DB_NAME:aisuda}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round
aisuda.datasource.username=${env.ISUDA_DB_USER:aisuda}
aisuda.datasource.password=${env.ISUDA_DB_PASSWORD:MuYoLdc\$}
aisuda.datasource.driver-class-name=${env.ISUDA_DB_DRIVER:com.mysql.jdbc.Driver}
# 使用oracle
#aisuda.datasource.type=oracle
#aisuda.datasource.url=jdbc:oracle:thin:@localhost:11521:HELOWIN
#aisuda.datasource.username=aisuda
#aisuda.datasource.password=MuYoLdc\$
#aisuda.datasource.driver-class-name=oracle.jdbc.OracleDriver
# 用户数据模型配置（使用内置数据源会连接到此数据库）
inner.datasource.host=${env.ISUDA_CUSTOM_DB_HOST:host.docker.internal}
inner.datasource.port=${env.ISUDA_CUSTOM_DB_PORT:3303}
inner.datasource.database=${env.ISUDA_CUSTOM_DB_NAME:innerdb}
inner.datasource.url=jdbc:${env.ISUDA_CUSTOM_DB_TYPE:mysql}://${env.ISUDA_CUSTOM_DB_HOST:host.docker.internal}:${env.ISUDA_CUSTOM_DB_PORT:3303}/${env.ISUDA_CUSTOM_DB_NAME:innerdb}?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=round
inner.datasource.username=${env.ISUDA_CUSTOM_DB_USER:aisuda}
inner.datasource.password=${env.ISUDA_CUSTOM_DB_PASSWORD:MuYoLdc\$}
inner.datasource.driver-class-name=${env.ISUDA_CUSTOM_DB_DRIVER:com.mysql.jdbc.Driver}
outer.datasource.env=dev
#flyway 默认使用代码配置
spring.flyway.enabled=false
aisuda.flyway.enabled=true
aisuda.flyway.clean-disabled=true
aisuda.flyway.baseline-on-migrate=true
aisuda.flyway.table=aisuda_flyway_history
aisuda.flyway.locations=classpath:db/${env.ISUDA_DB_TYPE:mysql}/migration
# oauth认证
aisuda.oauth.authorize.url=${env.ISUDA_OAUTH_AUTHORIZE_URL:http://localhost:8282/auth/request/path}
aisuda.oauth.token.url=${env.ISUDA_OAUTH_TOKEN_URL:http://localhost:8282/access/token/request}
aisuda.oauth.client.id=${env.ISUDA_OAUTH_CLIENT_ID:dummy_client_id}
aisuda.oauth.clirnt.secret=${env.ISUDA_OAUTH_CLIENT_SECRET:dummy_client_secret}
aisuda.oauth.scope=${env.ISUDA_OAUTH_SCOPE:email}
aisuda.oauth.info.url=${env.ISUDA_OAUTH_INFO_URL:http://localhost:8282/auth/userinfo}
# oauth返回的userinfo配置
aisuda.oauth.id.field=${env.ISUDA_OAUTH_ID_FIELD:id}
aisuda.oauth.name.field=${env.ISUDA_OAUTH_NAME_FIELD:name}
aisuda.oauth.display.field=${env.ISUDA_OAUTH_DISPLAY_FIELD:displayName}
aisuda.oauth.email.field=${env.ISUDA_OAUTH_EMAIL_FIELD:email}
aisuda.oauth.email.suffix=${env.ISUDA_OAUTH_EMAIL_SUFFIX:autogenerated@baidu.com}
# 第三方认证
aisuda.third.auth.authorize.url=${env.ISUDA_THIRD_AUTH_AUTHORIZE_URL:http://localhost:8899/login?callback={{callback}}}
aisuda.third.auth.profile.url=${env.ISUDA_THIRD_AUTH_PROFILE_URL:http://localhost:8081/third/userinfo?code={{code}}}
aisuda.third.auth.code.field=${env.ISUDA_THIRD_AUTH_CODE_FIELD:code}
# 邮件服务器相关配置
spring.mail.host=${env.ISUDA_EMAIL_HOST}
spring.mail.port=${env.ISUDA_EMAIL_PORT}
# 个人账户和密码（注：密码是加密后的授权码）
spring.mail.username=${env.ISUDA_EMAIL_USER:username}
spring.mail.password=${env.ISUDA_EMAIL_PASS:password}
spring.mail.default-encoding=UTF-8
# 邮件服务其他配置
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=3000
spring.mail.properties.mail.smtp.writetimeout=5000
# api转发是否禁止访问内网，true表示禁止访问内网，false表示允许访问内网
aisuda.disable.access.private.ip=${env.ISUDA_DISABLE_ACCESS_PRIVATE_IP:false}

# ldap
ldap.base.url=${env.ISUDA_LDAP_URL:ldap://ldap.forumsys.com:389}
ldap.base.bind.dc=${env.ISUDA_LDAP_BIND_DN:cn=read-only-admin,ou=mathematicians,dc=example,dc=com}
ldap.search.user.search.base=${env.ISUDA_LDAP_SEARCH_BASE:dc=example,dc=com}
ldap.search.user.filter=${env.ISUDA_LDAP_SEARCH_FILTER:(uid={0})}
ldap.base.credentials=${env.ISUDA_LDAP_BIND_CREDENTIALS:password}
ldap.email.attribute=${env.ISUDA_LDAP_EMAIL_ATTRIBUTE:mail}
ldap.nickname.attribute=${env.ISUDA_LDAP_NICKNAME_ATTRIBUTE:cn}
ldap.name.attribute=${env.ISUDA_LDAP_NAME_ATTRIBUTE:uid}
# cas
cas.base.url=${env.ISUDA_CAS2_BASE_URL://localhost:8080}
cas.authorize.path=${env.ISUDA_CAS2_AUTHORIZE_URL:/cas/login}
cas.validate.path=${env.ISUDA_CAS2_VALIDATE_URL:/cas/serviceValidate}
cas.email.attribute=${env.ISUDA_CAS2_EMAIL_FIELD:mail}
cas.email.suffix=${env.ISUDA_CAS2_EMAIL_SUFFIX:@baidu-int.com}
cas.display.attribute=${env.ISUDA_CAS2_DISPLAY_FIELD:display}
cas.name.attribute=${env.ISUDA_CAS2_NAME_FIELD:name}
cas.id.attribute=${env.ISUDA_CAS2_ID_FIELD:id}

isuda.auth.enabled.list=${env.ISUDA_AUTH_ENABLED_LIST}
auth.enabled.list=${env.AUTH_ENABLED_LIST}
aisuda.login.logo=${env.LOGIN_LOGO}
aisuda.login.background=${env.LOGIN_BACKGROUND}