version: '3'
services:
  web:
    depends_on:
      - db-engine
      - db-user
      - redis
    restart: on-failure
#    build: .
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    image: ${REPOSITORY:-registry.baidubce.com/aisuda/engine}:${VERSION:-latest}
    deploy:
      restart_policy:
        condition: on-failure
        delay: 10s
        window: 180s
        max_attempts: 3
      resources:
        limits:
          cpus: '4'
          memory: 4G
    volumes:
      - ${APP_DIR:-./app}:/app-engine/app
      - ${CONF_DIR:-./conf}:/app-engine/conf
      - ${LOG_DIR:-./log}:/app-engine/log
      - ${WEBROOT_DIR:-./webroot}:/app-engine/webroot
    ports:
      - '8899:8899'
    healthcheck:
      test: [ "CMD", "curl" ,"-f", "http://localhost:8899" ]
      interval: 60s
      timeout: 15s
      retries: 3
  db-engine:
    image: registry.baidubce.com/aisuda/mysql:5.7
    command:
      [
          'mysqld',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--skip-character-set-client-handshake',
          '--default-authentication-plugin=mysql_native_password',
          '--max-allowed-packet=1073741824',
          '--sort-buffer-size=512K',
          '--max-connections=4096'
      ]
    logging:
      driver: none
    volumes:
      - ${DB_DATA_DIR:-./db-data}/engine:/var/lib/mysql
    ports:
      - '3304:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=aisuda
      # 实际密码是'MuYoLdc$', 另一个'$'为转义符
      - MYSQL_PASSWORD=MuYoLdc$$
      - MYSQL_DATABASE=aisuda
  db-user:
    image: registry.baidubce.com/aisuda/mysql:5.7
    command:
      [
          'mysqld',
          '--character-set-server=utf8mb4',
          '--collation-server=utf8mb4_unicode_ci',
          '--skip-character-set-client-handshake',
          '--default-authentication-plugin=mysql_native_password',
          '--max-allowed-packet=1073741824',
          '--sort-buffer-size=512K',
          '--max-connections=4096'
      ]
    logging:
      driver: none
    volumes:
      # 用app/sourceSql文件夹下的建表语句初始化数据库
      - ${APP_DIR:-./app}/sourceSql:/docker-entrypoint-initdb.d
      - ${DB_DATA_DIR:-./db-data}/user:/var/lib/mysql
    ports:
      - '3303:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=aisuda
      # 实际密码是'MuYoLdc$', 另一个'$'为转义符
      - MYSQL_PASSWORD=MuYoLdc$$
      - MYSQL_DATABASE=innerdb
  redis:
    image: registry.baidubce.com/aisuda/redis:5
    command: [ 'redis-server' ]
    ports:
      - '6377:6379'
    logging:
      driver: none
    volumes:
      - ${REDIS_DATA_DIR:-./redis-data}:/data